import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import ExcelJS from "exceljs";
import JSZip from "jszip";
import { createBuiltinToolRegistry } from "./tool-registry.js";

async function workspace(t) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "newbrain-artifact-test-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  return root;
}

async function create(t, input) {
  const root = await workspace(t);
  const result = await createBuiltinToolRegistry().invoke("artifact.create", input, { workspacePath: root, shellEnv: process.env });
  assert.equal(result.ok, true, result.output);
  assert.equal(result.artifact.verified, true);
  return { root, result, bytes: await fs.readFile(path.join(root, input.targetPath)) };
}

test("artifact.create exposes a bounded native office generator", () => {
  const descriptor = createBuiltinToolRegistry().get("artifact.create");
  assert.deepEqual(descriptor.inputSchema.properties.format.enum, ["pdf", "pptx", "html", "xlsx", "docx"]);
  assert.equal(descriptor.requiresApproval, false);
});

test("creates a real PDF with an embedded document structure", async (t) => {
  const { bytes, result } = await create(t, { targetPath: "outputs/report.pdf", title: "Quality Report", sections: [{ heading: "Summary", body: "A native PDF generated by NewBrain.", bullets: ["Verified", "Reusable"] }] });
  assert.equal(bytes.subarray(0, 5).toString("ascii"), "%PDF-");
  assert.match(bytes.subarray(-32).toString("latin1"), /%%EOF/);
  assert.equal(result.artifact.type, "application/pdf");
});

test("renders Markdown content into PDF without raw Markdown markers", async (t) => {
  const { markdownToSections, stripInlineMarkdown } = await import("./artifact-generator.js");
  assert.equal(stripInlineMarkdown("**重点**与`代码`及[链接](https://example.com)"), "重点与代码及链接");
  assert.deepEqual(markdownToSections([
    "# 案例研究",
    "",
    "这是**正文**第一段。",
    "",
    "## 做法",
    "- 创新驱动",
    "- 绿色转型",
    "",
    "一、总体要求",
    "坚持因地制宜。"
  ].join("\n")), [
    { heading: "案例研究", body: "这是正文第一段。", bullets: [] },
    { heading: "做法", body: "", bullets: ["创新驱动", "绿色转型"] },
    { heading: "一、总体要求", body: "坚持因地制宜。", bullets: [] }
  ]);

  const markdown = [
    "# 因地制宜发展新质生产力",
    "",
    "各地应**坚持**创新驱动。",
    "",
    "## 重点做法",
    "- 产业升级",
    "- 绿色发展",
    "",
    "```json",
    "{\"task\":\"should not appear\"}",
    "```"
  ].join("\n");
  const parsedSections = markdownToSections(markdown);
  const flattened = parsedSections.map((section) => [section.heading, section.body, ...section.bullets].join("\n")).join("\n");
  assert.match(flattened, /因地制宜发展新质生产力/);
  assert.match(flattened, /坚持创新驱动/);
  assert.match(flattened, /产业升级/);
  assert.doesNotMatch(flattened, /#|##|\*\*|```|should not appear/);

  const { bytes, root, result } = await create(t, {
    targetPath: "outputs/markdown.pdf",
    title: "政务写作交付文档",
    format: "pdf",
    content: markdown
  });
  assert.equal(result.ok, true);
  assert.equal(bytes.subarray(0, 5).toString("ascii"), "%PDF-");
  // PDFKit with CJK fonts embeds text as glyphs; assert the generator path used cleaned sections
  // and that raw Markdown markers are not present as literal ASCII in the PDF stream.
  assert.doesNotMatch(bytes.toString("latin1"), /##\s*重点做法|\*\*坚持\*\*|```json|should not appear/);
  assert.equal(await fs.stat(path.join(root, "outputs", "markdown.pdf")).then((stat) => stat.isFile()), true);
});

test("creates a reopenable PPTX with slide OOXML", async (t) => {
  const { bytes, root } = await create(t, {
    targetPath: "outputs/deck.pptx",
    title: "Release Review",
    slides: [
      { title: "Release Review", subtitle: "2026 Q3", layout: "title" },
      { title: "Outcome", body: "Native PowerPoint output", bullets: ["Openable", "Structured"], layout: "bullets" },
      { title: "谢谢", body: "欢迎提问", layout: "closing" }
    ]
  });
  const archive = await JSZip.loadAsync(bytes);
  assert.ok(archive.file("ppt/presentation.xml"));
  assert.ok(archive.file("ppt/slides/slide1.xml"));
  assert.ok(archive.file("ppt/slides/slide2.xml"));
  assert.match(await archive.file("ppt/slides/slide2.xml").async("string"), /Native PowerPoint output/);
  const companion = await fs.readFile(path.join(root, "outputs", "deck.slides.html"), "utf8");
  assert.match(companion, /Release Review/);
  assert.match(companion, /title-slide|closing-slide/);
});

test("creates a PPTX with native chart and timeline slides", async (t) => {
  const { bytes } = await create(t, {
    targetPath: "outputs/analytics.pptx",
    title: "市场分析",
    slides: [
      { title: "市场分析", layout: "title" },
      {
        title: "销量趋势",
        layout: "chart",
        chart: {
          type: "bar",
          categories: ["2022", "2023", "2024"],
          series: [{ name: "销量", values: [120, 168, 215] }]
        }
      },
      {
        title: "实施阶段",
        layout: "timeline",
        phases: [
          { label: "P1", title: "调研", body: "需求访谈" },
          { label: "P2", title: "试点", body: "上线验证" }
        ]
      }
    ]
  });
  const archive = await JSZip.loadAsync(bytes);
  assert.ok(archive.file("ppt/charts/chart1.xml") || archive.file("ppt/embeddings/"));
  assert.ok(archive.file("ppt/slides/slide3.xml"));
});

test("creates a web-first HTML slide deck", async (t) => {
  const { root, result } = await create(t, {
    targetPath: "outputs/briefing.html",
    format: "html",
    title: "市场简报",
    slides: [
      { title: "市场简报", subtitle: "简洁大气", layout: "title" },
      { title: "核心结论", bullets: ["渗透率提升", "价格带下沉", "供应链本地化"], layout: "bullets" }
    ]
  });
  assert.equal(result.ok, true);
  const html = await fs.readFile(path.join(root, "outputs", "briefing.html"), "utf8");
  assert.match(html, /市场简报/);
  assert.match(html, /viewport/);
  assert.match(html, /ArrowRight/);
});

test("creates a reopenable XLSX preserving typed values", async (t) => {
  const { root } = await create(t, { targetPath: "outputs/data.xlsx", sheets: [{ name: "Metrics", rows: [["Metric", "Value"], ["Completion", 98], ["Passed", true]] }] });
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(path.join(root, "outputs/data.xlsx"));
  const sheet = workbook.getWorksheet("Metrics");
  assert.equal(sheet.getCell("B2").value, 98);
  assert.equal(sheet.getCell("B3").value, true);
  assert.equal(sheet.autoFilter, "A1:B3");
});

test("creates a reopenable DOCX with document OOXML", async (t) => {
  const { bytes } = await create(t, { targetPath: "outputs/brief.docx", title: "Native Document", sections: [{ heading: "Overview", body: "Word output generated without a temporary script." }] });
  const archive = await JSZip.loadAsync(bytes);
  assert.ok(archive.file("word/document.xml"));
  assert.match(await archive.file("word/document.xml").async("string"), /Word output generated without a temporary script/);
});

test("rejects extension mismatches and projects artifact paths into outputs", async (t) => {
  const root = await workspace(t);
  const registry = createBuiltinToolRegistry();
  const mismatch = await registry.invoke("artifact.create", { targetPath: "bad.txt", format: "pdf" }, { workspacePath: root, shellEnv: process.env });
  assert.equal(mismatch.ok, false);
  assert.match(mismatch.output, /extension must be \.pdf/);
  const projected = await registry.invoke("artifact.create", {
    targetPath: "../escape.pdf",
    format: "pdf"
  }, { workspacePath: root, shellEnv: process.env });
  assert.equal(projected.ok, true, projected.output);
  assert.equal(projected.artifact.path, "outputs/escape.pdf");
  assert.equal(await fs.stat(path.join(root, "outputs", "escape.pdf")).then((stat) => stat.isFile()), true);
});

test("strips HTML/XML chrome so PDF does not print raw tags", async (t) => {
  const { markdownToSections, normalizeArtifactMarkup } = await import("./artifact-generator.js");
  const markup = [
    "<document>",
    '<font family="SimSun" size="12" />',
    '<margins top="2.5cm" bottom="2.5cm" left="2.8cm" right="2.8cm" />',
    "<h1>《矿产资源法实施条例》宣传宣讲稿</h1>",
    '<p align="center" color="gray">宣讲对象：社会公众</p>',
    "<hr />",
    "<h2>开场导语</h2>",
    "<p>同志们，今天我们一起学习实施条例。</p>",
    "<p><b>第一个问题：矿产资源到底归谁？</b></p>",
    "</document>"
  ].join("\n");
  const plain = normalizeArtifactMarkup(markup);
  assert.doesNotMatch(plain, /<\/?[a-z]/i);
  assert.match(plain, /宣传宣讲稿/);
  assert.match(plain, /开场导语/);
  assert.match(plain, /同志们/);
  assert.match(plain, /第一个问题/);

  const sections = markdownToSections(markup);
  assert.ok(sections.some((section) => /宣传宣讲稿|开场导语/.test(section.heading)));
  assert.ok(sections.some((section) => section.body.includes("同志们")));

  const { bytes, result } = await create(t, {
    targetPath: "outputs/lecture.pdf",
    format: "pdf",
    title: "宣传宣讲稿",
    content: markup
  });
  assert.equal(bytes.subarray(0, 5).toString("ascii"), "%PDF-");
  assert.equal(result.ok, true);
});

test("document.create_pdf accepts structured sections and rejects HTML dumps", async (t) => {
  const { validateDocumentCreateInput, looksLikeHtmlDocumentDump } = await import("./artifact-generator.js");
  assert.equal(looksLikeHtmlDocumentDump("<document><p>x</p></document>"), true);
  assert.throws(
    () => validateDocumentCreateInput({
      title: "宣讲稿",
      content: "<document><font /><p>同志们</p><h1>标题</h1></document>"
    }, "pdf"),
    /rejects HTML\/XML/
  );
  const normalized = validateDocumentCreateInput({
    title: "矿产资源法宣讲稿",
    sections: [
      { heading: "开场导语", body: "同志们，今天一起学习实施条例。", bullets: ["国家所有", "依法开采"] }
    ]
  }, "pdf");
  assert.equal(normalized.format, "pdf");
  assert.equal(normalized.targetPath, "outputs/矿产资源法宣讲稿.pdf");
  assert.equal(normalized.sections[0].heading, "开场导语");

  const root = await workspace(t);
  const result = await createBuiltinToolRegistry().invoke("document.create_pdf", {
    title: "宣传宣讲稿",
    sections: [{ heading: "一、开场", body: "同志们：今天宣讲实施条例。" }]
  }, { workspacePath: root, shellEnv: process.env });
  assert.equal(result.ok, true, result.output);
  assert.equal(result.artifact.path, "outputs/宣传宣讲稿.pdf");
  assert.equal(result.artifact.format, "pdf");
});

test("localizes ASCII double quotes to Chinese curly quotes in Chinese prose", async () => {
  const { localizeChineseDoubleQuotes, stripInlineMarkdown } = await import("./artifact-generator.js");
  assert.equal(
    localizeChineseDoubleQuotes('他说"你好"然后离开。'),
    "他说\u201c你好\u201d然后离开。"
  );
  assert.equal(
    localizeChineseDoubleQuotes('He said "hello" then left.'),
    'He said "hello" then left.'
  );
  assert.equal(
    localizeChineseDoubleQuotes("各地坚持\uFF02创新驱动\uFF02不动摇。"),
    "各地坚持\u201c创新驱动\u201d不动摇。"
  );
  assert.equal(
    localizeChineseDoubleQuotes("他已说\u201c你好\"然后离开。"),
    "他已说\u201c你好\u201d然后离开。"
  );
  assert.equal(
    stripInlineMarkdown('各地应**坚持**"创新驱动"。'),
    "各地应坚持\u201c创新驱动\u201d。"
  );
});

test("document.create_docx writes Chinese curly quotes into Word XML", async (t) => {
  const root = await workspace(t);
  const result = await createBuiltinToolRegistry().invoke("document.create_docx", {
    title: "工作总结",
    sections: [{ heading: "概述", body: '全年坚持"稳中求进"工作总基调。' }]
  }, { workspacePath: root, shellEnv: process.env });
  assert.equal(result.ok, true, result.output);
  const bytes = await fs.readFile(path.join(root, result.artifact.path));
  const archive = await JSZip.loadAsync(bytes);
  const xml = await archive.file("word/document.xml").async("string");
  assert.match(xml, /\u201c稳中求进\u201d/);
  assert.doesNotMatch(xml, /"稳中求进"/);
});

test("document.create_docx merges thread delivery style into Word XML", async (t) => {
  const root = await workspace(t);
  const result = await createBuiltinToolRegistry().invoke("document.create_docx", {
    title: "版式报告",
    sections: [{ heading: "正文", body: "第二轮仍应使用记住的版式。" }]
  }, {
    workspacePath: root,
    shellEnv: process.env,
    deliveryPreferences: {
      thread: {
        version: 1,
        domains: {
          "document.style": {
            scope: "thread",
            values: { fontFamily: "宋体", fontSizePt: 12, lineSpacing: 1.5 },
            summary: "宋体 12pt 行距1.5"
          }
        }
      }
    }
  });
  assert.equal(result.ok, true, result.output);
  assert.match(result.output, /Applied delivery style/);
  assert.equal(result.artifact.style?.fontFamily, "SimSun");
  const bytes = await fs.readFile(path.join(root, result.artifact.path));
  const archive = await JSZip.loadAsync(bytes);
  const xml = await archive.file("word/document.xml").async("string");
  assert.match(xml, /w:ascii="SimSun"|w:eastAsia="SimSun"|SimSun/);
});

test("document.create_docx localizes ASCII quotes inside structured table rows", async (t) => {
  const root = await workspace(t);
  const result = await createBuiltinToolRegistry().invoke("document.create_docx", {
    title: "对照表",
    rows: [["层次", "要点"], ["前瞻性", '坚持"稳中求进"']]
  }, { workspacePath: root, shellEnv: process.env });
  assert.equal(result.ok, true, result.output);
  const bytes = await fs.readFile(path.join(root, result.artifact.path));
  const archive = await JSZip.loadAsync(bytes);
  const xml = await archive.file("word/document.xml").async("string");
  assert.match(xml, /\u201c稳中求进\u201d/);
  assert.doesNotMatch(xml, /"稳中求进"/);
});

test("keeps Markdown pipe tables as Word tbl instead of one collapsed paragraph", async (t) => {
  const { splitMarkdownTables } = await import("./artifact-generator.js");
  assert.deepEqual(splitMarkdownTables([
    "说明",
    "",
    "| 层次 | 逗号一 | 逗号二 |",
    "| --- | --- | --- |",
    "| 前瞻性 | 背景 | 做法 |",
    "| 全局性 | 背景 | 做法 |"
  ].join("\n")), {
    text: "说明",
    tables: [
      [
        ["层次", "逗号一", "逗号二"],
        ["前瞻性", "背景", "做法"],
        ["全局性", "背景", "做法"]
      ]
    ]
  });

  const { bytes } = await create(t, {
    targetPath: "outputs/对照表.docx",
    format: "docx",
    title: "三层次三逗号对照表",
    sections: [{
      heading: "说明",
      body: [
        "| 层次 | 逗号一 | 逗号二 |",
        "| --- | --- | --- |",
        "| 前瞻性 | 背景总结 | 做法 |"
      ].join("\n")
    }]
  });
  const archive = await JSZip.loadAsync(bytes);
  const xml = await archive.file("word/document.xml").async("string");
  assert.match(xml, /<w:tbl[\s>]/);
  assert.match(xml, /前瞻性/);
  assert.doesNotMatch(xml, /\| 层次 \| 逗号一 \| 逗号二 \|前瞻性/);
});

test("document.create_docx accepts structured rows for comparison tables", async (t) => {
  const root = await workspace(t);
  const result = await createBuiltinToolRegistry().invoke("document.create_docx", {
    title: "对照表",
    rows: [["层次", "要点"], ["前瞻性", "看得远"], ["战略性", "抓得实"]]
  }, { workspacePath: root, shellEnv: process.env });
  assert.equal(result.ok, true, result.output);
  const bytes = await fs.readFile(path.join(root, result.artifact.path));
  const archive = await JSZip.loadAsync(bytes);
  const xml = await archive.file("word/document.xml").async("string");
  assert.match(xml, /<w:tbl[\s>]/);
  assert.match(xml, /看得远/);
});

test("coerces page-size format a4 and synthesizes missing targetPath", async (t) => {
  const { validateArtifactCreateInput } = await import("./artifact-generator.js");
  assert.deepEqual(
    validateArtifactCreateInput({
      format: "a4",
      title: "矿产资源法宣讲稿",
      content: "同志们：今天宣讲实施条例。"
    }),
    {
      format: "pdf",
      title: "矿产资源法宣讲稿",
      content: "同志们：今天宣讲实施条例。",
      targetPath: "outputs/矿产资源法宣讲稿.pdf"
    }
  );
  const root = await workspace(t);
  const result = await createBuiltinToolRegistry().invoke("artifact.create", {
    format: "a4",
    title: "宣传宣讲稿",
    content: "一、开场说明。\n二、重点内容。"
  }, { workspacePath: root, shellEnv: process.env });
  assert.equal(result.ok, true, result.output);
  assert.equal(result.artifact.path, "outputs/宣传宣讲稿.pdf");
  assert.equal(result.artifact.format, "pdf");
  const bytes = await fs.readFile(path.join(root, result.artifact.path));
  assert.equal(bytes.subarray(0, 5).toString("ascii"), "%PDF-");
});
